#!/bin/bash

DOCKER=$(which docker)
IMAGENAME=tor
IMAGEID=latest
TOR_VERSION=0.4.4.6

usage() {
  echo "Usage: $0 [build|run|clean]"
}

build () {
  ${DOCKER} build -t ${IMAGENAME}:${IMAGEID} .
}

run() {
  local role=$1
  local name=$2
  exec ${DOCKER} run -it \
       --name ${name} \
       -p 9050:9050 \
       -p 9051:9051 \
       -p 9001:9001 \
       -p 9030:9030 \
       ${IMAGENAME}:${IMAGEID} ${role}
}

clean() {
  docker ps | grep -v CONTAINER | awk '{print $1}' | xargs docker stop
  docker ps -a | grep -v CONTAINER | awk '{print $1}' | xargs docker rm
  rm -rf tor-${TOR_VERSION}*
}

# parse the arguments
while [ "$1" != "" ]; do
  PARAM=$1
  VALUE=$2
  case $PARAM in
    -h | --help)
      usage
      exit
      ;;
    build)
      build
      ;;
    relay)
      run "relay" $VALUE
      ;;
    dirauth)
      run "dirauth" "DirectoryAuthority"
      ;;
    clean)
      clean
      ;;
    *)
      echo "ERROR: unknown parameter \"$PARAM\""
      usage
      exit 1
      ;;
  esac
  shift
done
