#!/usr/bin/python3

import sys
from os.path import realpath, dirname

script_dir = dirname(realpath(__file__))

# This line is required so I can use the ting module
sys.path.append(script_dir + '/../')
from ting.echo_server import EchoServer

if __name__ == "__main__":
    echo_server = EchoServer()
    if not echo_server.is_running():
        echo_server.run()
