# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='timer.proto',
  package='ting',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0btimer.proto\x12\x04ting\"Y\n\x04Ting\x12\x10\n\x08time_sec\x18\x01 \x01(\x01\x12 \n\x05ptype\x18\x02 \x02(\x0e\x32\x11.ting.Ting.Packet\"\x1d\n\x06Packet\x12\t\n\x05\x43LOSE\x10\x00\x12\x08\n\x04TING\x10\x01'
)



_TING_PACKET = _descriptor.EnumDescriptor(
  name='Packet',
  full_name='ting.Ting.Packet',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CLOSE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=81,
  serialized_end=110,
)
_sym_db.RegisterEnumDescriptor(_TING_PACKET)


_TING = _descriptor.Descriptor(
  name='Ting',
  full_name='ting.Ting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_sec', full_name='ting.Ting.time_sec', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ptype', full_name='ting.Ting.ptype', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TING_PACKET,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=110,
)

_TING.fields_by_name['ptype'].enum_type = _TING_PACKET
_TING_PACKET.containing_type = _TING
DESCRIPTOR.message_types_by_name['Ting'] = _TING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ting = _reflection.GeneratedProtocolMessageType('Ting', (_message.Message,), {
  'DESCRIPTOR' : _TING,
  '__module__' : 'timer_pb2'
  # @@protoc_insertion_point(class_scope:ting.Ting)
  })
_sym_db.RegisterMessage(Ting)


# @@protoc_insertion_point(module_scope)
